### ISSUE TITLE
Error importing paymill

### ISSUE THREAD

**Issue by michaelsd** [paymill/paymill-python#13]
After installing with ```pip install paymill-wrapper``` and importing it in a brand new project with ```import paymill``` i receive the following error:

```
import paymill
  File "/Projects/paymill-test/venv/lib/python2.7/site-packages/paymill/__init__.py", line 3, in <module>
    from .paymill_context import PaymillContext
  File "/Projects/paymill-test/venv/lib/python2.7/site-packages/paymill/paymill_context.py", line 3, in <module>
    from .utils import http_client
ImportError: No module named utils
```
Is there something I'm missing? Env: MacOS 10.10 and Python 2.7

**Comment by yalnazov** [comment]
Hi @michaelsd,  

thanks for the report. I will take a look later on today.

Could you temporarily try to install the wrapper from a local clone of the project like this:
git clone https://github.com/paymill/paymill-python
cd paymill-python/ 
pip install .

Does this work for you?

**Comment by michaelsd** [comment]
Hi @yalnazov,

unfortunately I still receive the very same error message:

```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    import paymill
  File "/Projects/paymill-test/venv/lib/python2.7/site-packages/paymill/__init__.py", line 3, in <module>
    from .paymill_context import PaymillContext
  File "/Projects/paymill-test/venv/lib/python2.7/site-packages/paymill/paymill_context.py", line 3, in <module>
    from .utils import http_client
ImportError: No module named utils
```

Thank you very much for your help!

**Comment by yalnazov** [comment]
Hey @michaelsd, 

I can not reproduce the problems you are having after a local install. 

I just retested with virtualenv set to work with Python 2.7 and I managed to to import the paymill module without any errors and successfully  created and API request.

In order to be sure you are testing the same environment as I did, please follow these steps and let me know, if this now works for you:
'pip install virtualenv'
'git clone https://github.com/paymill/paymill-python'
'cd paymill-python/ '
'virtualenv -p /usr/bin/python2.7 venv'
'source venv/bin/activate'
'python'
'import python'

**Comment by yalnazov** [comment]
Hey @michaelsd, 

there was indeed a problem with the current distribution on PyPi, so I fixed & re-uploaded it.

Could you please test it on your side?

**Comment by michaelsd** [comment]
Thanks @yalnazov,
should the last command be ```import paymill```?

**Comment by michaelsd** [comment]
Great, it's working now! Thank you very much for your help.
